notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

env:
 - CC=gcc

addons:
 apt:
  packages:
   - build-essential
   - autoconf
   - pkg-config
   - zlib1g-dev
   - curl

install: true

language: perl

perl:
 - "5.22"
# - "5.16"

script:
 - ./setup.sh ~/wtsi-opt
